name: is_even_ai_firebase_vertexai
description: Check if a given number is even with the power of Firebase VertexAI using `package:is_even_ai_firebase_vertexai`
version: 1.0.0
repository: https://github.com/MichaelDark/is_even_ai

environment:
  sdk: ^3.5.0

dependencies:
  is_even_ai: ^1.0.0
  firebase_vertexai: ^1.0.4

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
