name: is_even_ai
description: Check if a number is even with the power of ✨AI✨
version: 1.0.0
repository: https://github.com/MichaelDark/is_even_ai

environment:
  sdk: ^3.5.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
